### ISSUE TITLE
interleaving ile alakalı

### ISSUE THREAD

**Issue by hakansrc** [hakansrc/mlv_inv#2]
@mesutto

hocam 2 level spwm için 2 inverter ile interleaving yaparken carrierları birbirinden 180 derece kaydırdım ve pwm şekillerini elde ettim. fakat kafamı karıştıran şu ki sonuç olarak bu iki voltage waveformu farklı ve bunları parallel bağlamak sağlıklı mı. aşağıda belirtmek istediğimi görebilirsiniz
![](https://lh3.googleusercontent.com/5t3a97JEzZ1kJIsaFMaq-Msg4lu720Xo_nFF0BYJuS2RgaoZRJ9CP24nJXRjqKoUZk7bGixfag7hPdmv4qKEhr9pbSCvUo6PGGmWGHQTfi4_dQOSHlQoGtbAoMzGYp4wwgQV3C2k78fMqE2QfsKY3hYGESOgaaoc8LkBLJcHhSptvYlpaA313kPXS210cWqPR5uorl-pTBDPKlCtpQAXrGrgdKkSuQeFJ5FJTYqm_JyIYx6CiHa6yJwXkDRL7R9zKhJRqOUlx4oq3eugVFp0CKCcfOuHEvlBXCn1xLV12f3cTbg4rAkjpdwYWQF_xQ0lujJVW1nu9x0dIeqfkOwhg2Nellm9jEw4E9O5GXqv5Vicex0R2N5MC4kwAa01U7_XH9ycmbfCmzvzwU7fQB_XW_h8nHu0vrJ8CuFAWqPGdmx2FYFUZwTrIwe9EUU8yzJUpnhiVxd7gzD9ekxpaGXpkC80TwDsoSs8OzV--GgittNnsjCf1Vt5WyKidMYxVWMaRECXWfv8NeCYkiprCKaUdUO-rl5rnPtG1S_1LjBKQ1yRSRrSCQzlsK0fYcjEblrfqv47Qt9Rxfvk-Pccrc0se61WdN9n-xxIsvcOTRrFfg=w590-h408-no)

ben bunları aşağıdaki gibi direk parallel olarak bağlayıp simüle ettiğimde voltage ve current waveformları olmaması gerektiği gibi çıkıyor. inverterlar arası circulate eden kiloamperler civarında akım geçişi falan görüyorum. Load a giden akım da çok distorted 50hz de bi waveform ama mantıklı seviyelerde magnitude a sahip. bu kilo amperleri engellemek için inverter çıkışlarına inductor(1mH) bağladığımda load akımı normal sinüs gibi oluyor ve circulate eden akım 40 50A lere kadar düşüyor fakat voltage waveformlar halen çok garip çünkü bu circulate eden akımlar DC linkteki voltajı çok değiştiriyor anladığım kadarıyla.

bağlantıda mı yanlışlık yapıyorum acaba onu sormak istemiştim yoksa inductor değerlerini yükseltmeyi mi denemeliyim.

bahsettiğim simulink dosyası repomda mlv_inv\spwm\2level spwm\parallel_two_level_spwm siz de simule ederseniz görebilirsiniz.

 ![](https://lh3.googleusercontent.com/g5PeSioS2k2Otaoa693BUjPgF134ABWGT0xpn6GAVWx3TfG-N0BHQQlQii1omD8ImE-DKk2jRW26IxIw_6bQhtMjT8kqm66hvyT-CV9d4AC22tde_FQ_nqfJnkkBSUOAZcWZr-5X1AGReuD451jd3o0bsh6IL6rAkAS5cg_vYxN3ztNxzRz55xOL4bBqsEECtWF-8ubrRojrtoklqzownuNZ_BVjkfZKebQ-ic-Umc8MtbREsVx4KGTEZHKIKm0rshBbNl-aC1lYFWAKN8F0EzizQuS85vEi8X66-IMm7hXcDpEDBM3q1bfiXR09vifvSNsgZa0lANeCpPX1G0JkNdT56YCp51AjF4EMP2KUCeXC_pskCdjnXdn6STYyZg7BcYdWPG8VI1et9DS0jK97Vek9gXdZPUrEk_9j18O2856W7hxospOIRFUqRV4TL7oDKTtgOsZcZvJNSQGb91yzAXiQ-zkzpnsh0-y2_rpKcBjbcazU_eSl6Kb8IF6tXLgJl3xFAQrF8LNI1NrSqF_c6O99j-A8fkP_9g3W5o2NmdIKkwT0KvRZHpeixdBkrcrz33G3RQOuk7lIxyVYEl5RuBhj11bC6N0fCe7tB4CulQ=w1757-h809-no)

**Comment by mesutto** [comment]
Merhaba Hakan,

Simulink dosyasına bakacağım. Muhtemelen bağlantı hatası vardır. Bahsettiğin sonuçları ve devreleri buraya da koyarsan iyi olur. Hatta yaptığın bütün simulasyon türleri için (2L-3L vs) bunu yaparsan çok iyi olur. Bakan kişi her zaman MATLAB'a erişemeyebilir.

**Comment by hakansrc** [comment]
Tamam hocam akşam atarım

**Comment by mesutto** [comment]
Bağlantı ters olmuş :) AC'yi değil DC'yi paralelleyeceğiz.

Gözüme çarpan noktalar:

1. 2L'da DC'nin orta noktasını bi yere bağlama. Gerek de yok zaten.
2. İki tane inverter düşün. Bunların DC+ ve DC-'larını birbirine paralel bağlayacaksın.
3. Her inverter için ayrı RLC load olacak (birbirine elektriksel olarak bağlanmayacak). Toplam güç 8kW ise 4-4 olacak şekilde ayarlayacaksın.

Konu ile ilgili biraz okuma yapsana, makale vs. Çok temel bir yerde takılmışsın çünkü.

Eline sağlık, kolay gelsin.

**Comment by hakansrc** [comment]
nedense bağlantı şekline hiç dikkat etmemişim hocam, ben genelde akımdaki switching frekansının gerçekleştirği harmoniği yoketmeye dair makalelere takılı kalmışım galiba. 

bi makaledeki şu cümleye takıldım ve hep taşıyıcılar arasındaki fazı pi/41 (2050Hz için) şeklinde kaydırmak istedim. 
        

> Since |F(idc)(m,n)| =2|F(idc1)| (m,n)cos(mκ/2),ifthe dominant harmonic component is located at mth switching frequency, the interleaving angle should be selected to π/m to eliminate it.


galiba yanlış noktaya takılmışım.
